#!/bin/sh

# Shell variables
# Generated by 'wal'
export wallpaper="{wallpaper}"

# Special
export background='{background}'
export foreground='{foreground}'
export cursor='{cursor}'

# Colors
export color0='{color0}'
export color1='{color1}'
export color2='{color2}'
export color3='{color3}'
export color4='{color4}'
export color5='{color5}'
export color6='{color6}'
export color7='{color7}'
export color8='{color8}'
export color9='{color9}'
export color10='{color10}'
export color11='{color11}'
export color12='{color12}'
export color13='{color13}'
export color14='{color14}'
export color15='{color15}'
export color0_alpha='#bb{color0.strip}'
export color1_alpha='#bb{color1.strip}'
export color2_alpha='#bb{color2.strip}'
export color3_alpha='#bb{color3.strip}'
export color4_alpha='#bb{color4.strip}'
export color5_alpha='#bb{color5.strip}'
export color6_alpha='#bb{color6.strip}'
export color7_alpha='#bb{color7.strip}'
export color8_alpha='#bb{color8.strip}'
export color9_alpha='#bb{color9.strip}'
export color10_alpha='#bb{color10.strip}'
export color11_alpha='#bb{color11.strip}'
export color12_alpha='#bb{color12.strip}'
export color13_alpha='#bb{color13.strip}'
export color14_alpha='#bb{color14.strip}'
export color15_alpha='#bb{color15.strip}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="$LS_COLORS:su=30;41:ow=30;42:st=30;44:"

