#!/bin/sh

if echo "$PATH" | grep -vq "$XDG_CONFIG_HOME/sway/scripts"; then
    PATH="$PATH:$XDG_CONFIG_HOME/sway/scripts"
fi

export MOZ_ENABLE_WAYLAND=1
export CLUTTER_BACKEND="wayland"
export ECORE_EVAS_ENGINE="wayland_egl"
export ELM_ENGINE="wayland_egl"
# JAVA
export _JAVA_AWT_WM_NONREPARENTING=1
# SDL: turn of if old game
export SDL_VIDEODRIVER="wayland"
# QT
export QT_AUTO_SCREEN_SCALE_FACTOR=-1
export QT_QPA_PLATFORM="wayland-egl;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_WAYLAND_FORCE_DPI=physical
# GTK
export GDK_BACKEND="wayland,x11"
