# Shell variables
# Generated by 'wal'
wallpaper="{wallpaper}"

# Special
background='{background}'
foreground='{foreground}'
cursor='{cursor}'

# Colors
color0='{color0}'
color1='{color1}'
color2='{color2}'
color3='{color3}'
color4='{color4}'
color5='{color5}'
color6='{color6}'
color7='{color7}'
color8='{color8}'
color9='{color9}'
color10='{color10}'
color11='{color11}'
color12='{color12}'
color13='{color13}'
color14='{color14}'
color15='{color15}'
color0_alpha='#bb{color0.strip}'
color1_alpha='#bb{color1.strip}'
color2_alpha='#bb{color2.strip}'
color3_alpha='#bb{color3.strip}'
color4_alpha='#bb{color4.strip}'
color5_alpha='#bb{color5.strip}'
color6_alpha='#bb{color6.strip}'
color7_alpha='#bb{color7.strip}'
color8_alpha='#bb{color8.strip}'
color9_alpha='#bb{color9.strip}'
color10_alpha='#bb{color10.strip}'
color11_alpha='#bb{color11.strip}'
color12_alpha='#bb{color12.strip}'
color13_alpha='#bb{color13.strip}'
color14_alpha='#bb{color14.strip}'
color15_alpha='#bb{color15.strip}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${{LS_COLORS}}:su=30;41:ow=30;42:st=30;44:"

