[manager]
ratio = [1,4,8]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true
linemode = "ctime"
show_hidden = true
scrolloff = 200
title_format = "yazi: {cwd}"

[preview]
wrap = "yes"
tab_size = 2
max_width = 1600
max_height = 1000
# cache_dir =
# image_delay = 0
image_filter = "nearest"
image_quality = 50
# sixel_fraction = "50"
# ueberzug_scale = "50"
# ueberzug_offset = "50"

# [opener]
# play = [
# 	{ run = 'mpv "$@"', orphan = true, for = "unix" },
# 	{ run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" }
# ]
# edit = [
# 	{ run = '$EDITOR "$@"', block = true, for = "unix" },
# 	{ run = "%EDITOR% %*",  block = true, for = "windows" },
# ]
# open = [
# 	{ run = 'xdg-open "$@"', desc = "Open" },
# ]

# [open]
# prepend_rules = [
# 	{ name = "*.json", use = "edit" },
#
# 	# Multiple openers for a single rule
# 	{ name = "*.html", use = [ "open", "edit" ] },
# ]
# append_rules = [
# 	{ name = "*", use = "my-fallback" },
# ]

# [tasks]
# micro_workers = 
# macro_workers = 
# bizarre_retry = 
# suppress_preload = 
# image_alloc =
# image_bound =

# [plugin]
# prepend_previewers = [
# 	# HEIC previewer
# 	{ mime = "image/heic", run = "heic" },
# ]
# previewers = [
# 	# HEIC previewer
# 	{ mime = "image/heic", run = "heic" },
# ]
# append_previewers = [
# 	# My fallback previewer
# 	{ name = "*" , run = "binary" },
# ]
# prepend_preloaders = [
# 	# HEIC preloader
# 	{ mime = "image/heic", run = "heic" },
# ]
# preloaders = [
# 	# HEIC preloader
# 	{ mime = "image/heic", run = "heic" },
# ]
# append_preloaders = [
# 	# HEIC preloader
# 	{ mime = "image/heic", run = "heic" },
# ]

[which]
sort_by = "key"
sort_sensitive = false
sort_reverse = false
sort_translit = true
