[colors]
ansi = [
    "#313244",
    "#f38ba8",
    "#a6e3a1",
    "#fab387",
    "#89b4fa",
    "#cba6f7",
    "#74c7ec",
    "#bac2de",
]
brights = [
    "#6c7086",
    "#eba0ac",
    "#94e2d5",
    "#f9e2af",
    "#b4befe",
    "#f5c2e7",
    "#89dceb",
    "#cdd6f4",
]

background = "#1e1e2e"
foreground = "#cdd6f4"

compose_cursor = "#f2cdcd"
cursor_bg = "#f5e0dc"
cursor_border = "#f5e0dc"
cursor_fg = "#11111b"


selection_bg = "#585b70"
selection_fg = "#cdd6f4"

scrollbar_thumb = "#585b70"
split = "#6c7086"
visual_bell = "#313244"

[colors.indexed]
16 = "#fab387"
17 = "#f5e0dc"

[colors.tab_bar]
background = "#11111b"
inactive_tab_edge = "#313244"

[colors.tab_bar.active_tab]
bg_color = "#cba6f7"
fg_color = "#11111b"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#181825"
fg_color = "#cdd6f4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1e1e2e"
fg_color = "#cdd6f4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#313244"
fg_color = "#cdd6f4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#45475a"
fg_color = "#cdd6f4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
aliases = [
    "Gattopuccin Mocha (Gogh)",
    "gattopuccin-mocha",
]
author = "Catppuccin Org & 50nj1ku"
name = "Gattopuccin Mocha"
origin_url = "https://github.com/catppuccin/wezterm"
wezterm_version = "20220807-113146-c2fee766"
